package com.dylan.glasswidget.widget

// Generated by tools/build_clock_digits.py; do not edit.

import com.dylan.glasswidget.R
import com.dylan.glasswidget.data.ClockFace

/** Digit drawables 0-9 then the colon, for a face and glass colour. */
internal fun glyphTable(face: ClockFace, set: GlyphSet): IntArray = when (face) {
    ClockFace.Condensed -> when (set) {
        GlyphSet.Light -> intArrayOf(R.drawable.clock_condensed_light_0, R.drawable.clock_condensed_light_1, R.drawable.clock_condensed_light_2, R.drawable.clock_condensed_light_3, R.drawable.clock_condensed_light_4, R.drawable.clock_condensed_light_5, R.drawable.clock_condensed_light_6, R.drawable.clock_condensed_light_7, R.drawable.clock_condensed_light_8, R.drawable.clock_condensed_light_9, R.drawable.clock_condensed_light_colon)
        GlyphSet.Dark -> intArrayOf(R.drawable.clock_condensed_dark_0, R.drawable.clock_condensed_dark_1, R.drawable.clock_condensed_dark_2, R.drawable.clock_condensed_dark_3, R.drawable.clock_condensed_dark_4, R.drawable.clock_condensed_dark_5, R.drawable.clock_condensed_dark_6, R.drawable.clock_condensed_dark_7, R.drawable.clock_condensed_dark_8, R.drawable.clock_condensed_dark_9, R.drawable.clock_condensed_dark_colon)
        GlyphSet.Accent -> intArrayOf(R.drawable.clock_condensed_accent_0, R.drawable.clock_condensed_accent_1, R.drawable.clock_condensed_accent_2, R.drawable.clock_condensed_accent_3, R.drawable.clock_condensed_accent_4, R.drawable.clock_condensed_accent_5, R.drawable.clock_condensed_accent_6, R.drawable.clock_condensed_accent_7, R.drawable.clock_condensed_accent_8, R.drawable.clock_condensed_accent_9, R.drawable.clock_condensed_accent_colon)
    }
    ClockFace.Rounded -> when (set) {
        GlyphSet.Light -> intArrayOf(R.drawable.clock_rounded_light_0, R.drawable.clock_rounded_light_1, R.drawable.clock_rounded_light_2, R.drawable.clock_rounded_light_3, R.drawable.clock_rounded_light_4, R.drawable.clock_rounded_light_5, R.drawable.clock_rounded_light_6, R.drawable.clock_rounded_light_7, R.drawable.clock_rounded_light_8, R.drawable.clock_rounded_light_9, R.drawable.clock_rounded_light_colon)
        GlyphSet.Dark -> intArrayOf(R.drawable.clock_rounded_dark_0, R.drawable.clock_rounded_dark_1, R.drawable.clock_rounded_dark_2, R.drawable.clock_rounded_dark_3, R.drawable.clock_rounded_dark_4, R.drawable.clock_rounded_dark_5, R.drawable.clock_rounded_dark_6, R.drawable.clock_rounded_dark_7, R.drawable.clock_rounded_dark_8, R.drawable.clock_rounded_dark_9, R.drawable.clock_rounded_dark_colon)
        GlyphSet.Accent -> intArrayOf(R.drawable.clock_rounded_accent_0, R.drawable.clock_rounded_accent_1, R.drawable.clock_rounded_accent_2, R.drawable.clock_rounded_accent_3, R.drawable.clock_rounded_accent_4, R.drawable.clock_rounded_accent_5, R.drawable.clock_rounded_accent_6, R.drawable.clock_rounded_accent_7, R.drawable.clock_rounded_accent_8, R.drawable.clock_rounded_accent_9, R.drawable.clock_rounded_accent_colon)
    }
    ClockFace.Geometric -> when (set) {
        GlyphSet.Light -> intArrayOf(R.drawable.clock_geometric_light_0, R.drawable.clock_geometric_light_1, R.drawable.clock_geometric_light_2, R.drawable.clock_geometric_light_3, R.drawable.clock_geometric_light_4, R.drawable.clock_geometric_light_5, R.drawable.clock_geometric_light_6, R.drawable.clock_geometric_light_7, R.drawable.clock_geometric_light_8, R.drawable.clock_geometric_light_9, R.drawable.clock_geometric_light_colon)
        GlyphSet.Dark -> intArrayOf(R.drawable.clock_geometric_dark_0, R.drawable.clock_geometric_dark_1, R.drawable.clock_geometric_dark_2, R.drawable.clock_geometric_dark_3, R.drawable.clock_geometric_dark_4, R.drawable.clock_geometric_dark_5, R.drawable.clock_geometric_dark_6, R.drawable.clock_geometric_dark_7, R.drawable.clock_geometric_dark_8, R.drawable.clock_geometric_dark_9, R.drawable.clock_geometric_dark_colon)
        GlyphSet.Accent -> intArrayOf(R.drawable.clock_geometric_accent_0, R.drawable.clock_geometric_accent_1, R.drawable.clock_geometric_accent_2, R.drawable.clock_geometric_accent_3, R.drawable.clock_geometric_accent_4, R.drawable.clock_geometric_accent_5, R.drawable.clock_geometric_accent_6, R.drawable.clock_geometric_accent_7, R.drawable.clock_geometric_accent_8, R.drawable.clock_geometric_accent_9, R.drawable.clock_geometric_accent_colon)
    }
    ClockFace.Serif -> when (set) {
        GlyphSet.Light -> intArrayOf(R.drawable.clock_serif_light_0, R.drawable.clock_serif_light_1, R.drawable.clock_serif_light_2, R.drawable.clock_serif_light_3, R.drawable.clock_serif_light_4, R.drawable.clock_serif_light_5, R.drawable.clock_serif_light_6, R.drawable.clock_serif_light_7, R.drawable.clock_serif_light_8, R.drawable.clock_serif_light_9, R.drawable.clock_serif_light_colon)
        GlyphSet.Dark -> intArrayOf(R.drawable.clock_serif_dark_0, R.drawable.clock_serif_dark_1, R.drawable.clock_serif_dark_2, R.drawable.clock_serif_dark_3, R.drawable.clock_serif_dark_4, R.drawable.clock_serif_dark_5, R.drawable.clock_serif_dark_6, R.drawable.clock_serif_dark_7, R.drawable.clock_serif_dark_8, R.drawable.clock_serif_dark_9, R.drawable.clock_serif_dark_colon)
        GlyphSet.Accent -> intArrayOf(R.drawable.clock_serif_accent_0, R.drawable.clock_serif_accent_1, R.drawable.clock_serif_accent_2, R.drawable.clock_serif_accent_3, R.drawable.clock_serif_accent_4, R.drawable.clock_serif_accent_5, R.drawable.clock_serif_accent_6, R.drawable.clock_serif_accent_7, R.drawable.clock_serif_accent_8, R.drawable.clock_serif_accent_9, R.drawable.clock_serif_accent_colon)
    }
    ClockFace.Mono -> when (set) {
        GlyphSet.Light -> intArrayOf(R.drawable.clock_mono_light_0, R.drawable.clock_mono_light_1, R.drawable.clock_mono_light_2, R.drawable.clock_mono_light_3, R.drawable.clock_mono_light_4, R.drawable.clock_mono_light_5, R.drawable.clock_mono_light_6, R.drawable.clock_mono_light_7, R.drawable.clock_mono_light_8, R.drawable.clock_mono_light_9, R.drawable.clock_mono_light_colon)
        GlyphSet.Dark -> intArrayOf(R.drawable.clock_mono_dark_0, R.drawable.clock_mono_dark_1, R.drawable.clock_mono_dark_2, R.drawable.clock_mono_dark_3, R.drawable.clock_mono_dark_4, R.drawable.clock_mono_dark_5, R.drawable.clock_mono_dark_6, R.drawable.clock_mono_dark_7, R.drawable.clock_mono_dark_8, R.drawable.clock_mono_dark_9, R.drawable.clock_mono_dark_colon)
        GlyphSet.Accent -> intArrayOf(R.drawable.clock_mono_accent_0, R.drawable.clock_mono_accent_1, R.drawable.clock_mono_accent_2, R.drawable.clock_mono_accent_3, R.drawable.clock_mono_accent_4, R.drawable.clock_mono_accent_5, R.drawable.clock_mono_accent_6, R.drawable.clock_mono_accent_7, R.drawable.clock_mono_accent_8, R.drawable.clock_mono_accent_9, R.drawable.clock_mono_accent_colon)
    }
    ClockFace.Tall -> when (set) {
        GlyphSet.Light -> intArrayOf(R.drawable.clock_tall_light_0, R.drawable.clock_tall_light_1, R.drawable.clock_tall_light_2, R.drawable.clock_tall_light_3, R.drawable.clock_tall_light_4, R.drawable.clock_tall_light_5, R.drawable.clock_tall_light_6, R.drawable.clock_tall_light_7, R.drawable.clock_tall_light_8, R.drawable.clock_tall_light_9, R.drawable.clock_tall_light_colon)
        GlyphSet.Dark -> intArrayOf(R.drawable.clock_tall_dark_0, R.drawable.clock_tall_dark_1, R.drawable.clock_tall_dark_2, R.drawable.clock_tall_dark_3, R.drawable.clock_tall_dark_4, R.drawable.clock_tall_dark_5, R.drawable.clock_tall_dark_6, R.drawable.clock_tall_dark_7, R.drawable.clock_tall_dark_8, R.drawable.clock_tall_dark_9, R.drawable.clock_tall_dark_colon)
        GlyphSet.Accent -> intArrayOf(R.drawable.clock_tall_accent_0, R.drawable.clock_tall_accent_1, R.drawable.clock_tall_accent_2, R.drawable.clock_tall_accent_3, R.drawable.clock_tall_accent_4, R.drawable.clock_tall_accent_5, R.drawable.clock_tall_accent_6, R.drawable.clock_tall_accent_7, R.drawable.clock_tall_accent_8, R.drawable.clock_tall_accent_9, R.drawable.clock_tall_accent_colon)
    }
}
