package com.dylan.glasswidget.widget

import android.content.Context
import android.util.TypedValue
import android.view.Gravity
import android.view.View
import android.widget.RemoteViews
import androidx.compose.runtime.Composable
import androidx.glance.GlanceModifier
import androidx.glance.appwidget.AndroidRemoteViews
import com.dylan.glasswidget.R
import com.dylan.glasswidget.data.ClockStyle
import com.dylan.glasswidget.data.DatePreset
import com.dylan.glasswidget.data.HourMode
import com.dylan.glasswidget.data.WidgetAlignment

/**
 * Widget text is real TextViews/TextClocks wrapped in Glance's AndroidRemoteViews, in the system font.
 * (Launchers inflate widgets in a restricted context where custom fonts are ignored — which is why the
 * glass clock is drawn from images instead.)
 */

private fun RemoteViews.color(id: Int, day: Int, night: Int) {
    // Day/night pair (API 31+): the launcher swaps them itself when the system theme changes.
    setColorInt(id, "setTextColor", day, night)
}

/** 12h/24h patterns with or without the colon; HyperOS's lockscreen clock has none. */
internal fun clockFormats(hourMode: HourMode, colon: Boolean): Pair<String, String> {
    val sep = if (colon) ":" else ""
    val h12 = "h${sep}mm"
    val h24 = "HH${sep}mm"
    return when (hourMode) {
        HourMode.System -> h12 to h24
        HourMode.H12 -> h12 to h12
        HourMode.H24 -> h24 to h24
    }
}

private val GLYPH_VIEWS = intArrayOf(R.id.glyph0, R.id.glyph1, R.id.glyph2, R.id.glyph3, R.id.glyph4)

// Digit images 0-9 then the colon, per style and glass colour (generated by tools/build_clock_digits.py).
private val GLASS_GLYPHS = mapOf(
    GlyphSet.Light to intArrayOf(
        R.drawable.clock_light_0, R.drawable.clock_light_1, R.drawable.clock_light_2, R.drawable.clock_light_3,
        R.drawable.clock_light_4, R.drawable.clock_light_5, R.drawable.clock_light_6, R.drawable.clock_light_7,
        R.drawable.clock_light_8, R.drawable.clock_light_9, R.drawable.clock_light_colon,
    ),
    GlyphSet.Dark to intArrayOf(
        R.drawable.clock_dark_0, R.drawable.clock_dark_1, R.drawable.clock_dark_2, R.drawable.clock_dark_3,
        R.drawable.clock_dark_4, R.drawable.clock_dark_5, R.drawable.clock_dark_6, R.drawable.clock_dark_7,
        R.drawable.clock_dark_8, R.drawable.clock_dark_9, R.drawable.clock_dark_colon,
    ),
    GlyphSet.Accent to intArrayOf(
        R.drawable.clock_accent_0, R.drawable.clock_accent_1, R.drawable.clock_accent_2, R.drawable.clock_accent_3,
        R.drawable.clock_accent_4, R.drawable.clock_accent_5, R.drawable.clock_accent_6, R.drawable.clock_accent_7,
        R.drawable.clock_accent_8, R.drawable.clock_accent_9, R.drawable.clock_accent_colon,
    ),
)
private val CRYSTAL_GLYPHS = mapOf(
    GlyphSet.Light to intArrayOf(
        R.drawable.crystal_light_0, R.drawable.crystal_light_1, R.drawable.crystal_light_2, R.drawable.crystal_light_3,
        R.drawable.crystal_light_4, R.drawable.crystal_light_5, R.drawable.crystal_light_6, R.drawable.crystal_light_7,
        R.drawable.crystal_light_8, R.drawable.crystal_light_9, R.drawable.crystal_light_colon,
    ),
    GlyphSet.Dark to intArrayOf(
        R.drawable.crystal_dark_0, R.drawable.crystal_dark_1, R.drawable.crystal_dark_2, R.drawable.crystal_dark_3,
        R.drawable.crystal_dark_4, R.drawable.crystal_dark_5, R.drawable.crystal_dark_6, R.drawable.crystal_dark_7,
        R.drawable.crystal_dark_8, R.drawable.crystal_dark_9, R.drawable.crystal_dark_colon,
    ),
    GlyphSet.Accent to intArrayOf(
        R.drawable.crystal_accent_0, R.drawable.crystal_accent_1, R.drawable.crystal_accent_2, R.drawable.crystal_accent_3,
        R.drawable.crystal_accent_4, R.drawable.crystal_accent_5, R.drawable.crystal_accent_6, R.drawable.crystal_accent_7,
        R.drawable.crystal_accent_8, R.drawable.crystal_accent_9, R.drawable.crystal_accent_colon,
    ),
)

private fun glyphRes(c: Char, style: ClockStyle, set: GlyphSet): Int {
    val table = (if (style == ClockStyle.Crystal) CRYSTAL_GLYPHS else GLASS_GLYPHS).getValue(set)
    return when {
        c == ':' -> table[10]
        c.isDigit() -> table[c - '0']
        else -> 0
    }
}

/**
 * The big clock. Glass/Crystal: [text] ("0745") drawn from the digit images, kept current by
 * [ClockTicker]. Solid: a system-font TextClock that ticks by itself. Give [modifier] a fixed height.
 */
@Composable
fun ClockDigits(
    context: Context,
    style: ClockStyle,
    text: String,
    spoken: String,
    hourMode: HourMode,
    colon: Boolean,
    alignment: WidgetAlignment,
    palette: GlassPalette,
    modifier: GlanceModifier,
) {
    val gravity =
        if (alignment == WidgetAlignment.Center) Gravity.CENTER else Gravity.START or Gravity.CENTER_VERTICAL
    val views = if (style.usesImages) {
        RemoteViews(context.packageName, R.layout.clock_digits).apply {
            GLYPH_VIEWS.forEachIndexed { i, id ->
                val res = text.getOrNull(i)?.let { glyphRes(it, style, palette.glyphs) } ?: 0
                if (res == 0) {
                    setViewVisibility(id, View.GONE)
                } else {
                    setImageViewResource(id, res)
                    setViewVisibility(id, View.VISIBLE)
                    setInt(id, "setImageAlpha", palette.glassAlpha)
                }
            }
            setInt(R.id.clockRow, "setGravity", gravity)
            setContentDescription(R.id.clockRow, spoken)
        }
    } else {
        val (f12, f24) = clockFormats(hourMode, colon)
        RemoteViews(context.packageName, R.layout.textclock_solid).apply {
            setCharSequence(R.id.clockText, "setFormat12Hour", f12)
            setCharSequence(R.id.clockText, "setFormat24Hour", f24)
            setInt(R.id.clockText, "setGravity", gravity)
            color(R.id.clockText, palette.textDay, palette.textNight)
        }
    }
    AndroidRemoteViews(views, modifier)
}

@Composable
fun DateText(context: Context, preset: DatePreset, sizeSp: Float, palette: GlassPalette) {
    val views = RemoteViews(context.packageName, R.layout.textclock_date).apply {
        setCharSequence(R.id.dateText, "setFormat12Hour", preset.pattern)
        setCharSequence(R.id.dateText, "setFormat24Hour", preset.pattern)
        setTextViewTextSize(R.id.dateText, TypedValue.COMPLEX_UNIT_SP, sizeSp)
        color(R.id.dateText, palette.textDay, palette.textNight)
    }
    AndroidRemoteViews(views)
}

enum class LabelStyle { Normal, Secondary, Emphasis }

@Composable
fun LabelText(
    context: Context,
    text: String,
    sizeSp: Float,
    palette: GlassPalette,
    style: LabelStyle = LabelStyle.Normal,
) {
    val layout = if (style == LabelStyle.Emphasis) R.layout.label_text_medium else R.layout.label_text
    val views = RemoteViews(context.packageName, layout).apply {
        setTextViewText(R.id.labelText, text)
        setTextViewTextSize(R.id.labelText, TypedValue.COMPLEX_UNIT_SP, sizeSp)
        if (style == LabelStyle.Secondary) color(R.id.labelText, palette.secondaryDay, palette.secondaryNight)
        else color(R.id.labelText, palette.textDay, palette.textNight)
    }
    AndroidRemoteViews(views)
}
