package com.dylan.glasswidget.data

// Generated by tools/build_clock_digits.py; do not edit.

/** Typefaces for the glass clock, with each face's digit and colon width/height ratios. */
enum class ClockFace(val key: String, val label: String, val digitAspect: Float, val colonAspect: Float) {
    Condensed("condensed", "Condensed", 0.4020f, 0.1841f),
    Rounded("rounded", "Rounded", 0.7626f, 0.3057f),
    Geometric("geometric", "Geometric", 0.7972f, 0.2894f),
    Serif("serif", "Serif", 0.7533f, 0.2890f),
    Mono("mono", "Mono", 0.7044f, 0.2911f),
    Tall("tall", "Tall", 0.5540f, 0.1949f);

    companion object {
        fun from(key: String?) = entries.firstOrNull { it.key == key } ?: Condensed
    }
}
